apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  source:
    path: Deployments
    repoURL: https://github.com/Ranjith-kumar533/ArgocdTest.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true
    automated:
      selfHeal: true
      prune: true
